[PHP]

session.gc_maxlifetime=3600
session.cookie_lifetime=0
upload_max_filesize=256M
post_max_size=256M

; Also set in 02-govcms-opcache.ini, which is the file copied into the CLI
; and test images. Keep the two values the same.
opcache.huge_code_pages=0
