ARG CLI_IMAGE
ARG LAGOON_IMAGE_VERSION
ARG COMPOSER_AUTH
FROM ${CLI_IMAGE} as cli

FROM uselagoon/php-8.1-cli-drupal:${LAGOON_IMAGE_VERSION}

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY --from=cli /app /app
COPY .docker/scripts/ /usr/bin/

# Don't restrict the memory limit for the test image.
RUN echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/99-memory-limit.ini

RUN cp -r /app/web/profiles/contrib/govcms/tests /app/ \
    && composer install -d /app/tests -n --ansi --prefer-dist --no-suggest \
    && chmod +x /usr/bin/lint-govcms \
    && chmod +x /usr/bin/lint-theme \
    && chmod +x /usr/bin/behat \
    && chmod +x /usr/bin/phpunit

COPY .docker/images/test/phpunit/phpunit.xml /app/tests/phpunit/
COPY .docker/images/test/phpunit/bootstrap.php /app/tests/phpunit/

# Ensure MySQL client can accept server max_allowed_packet
COPY .docker/images/govcms/mariadb-client.cnf /etc/my.cnf.d

# Ensure that drush and drush.launcher both work
ENV WEBROOT=web
