ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM govcms8dev/nginx-drupal:1.0.0-beta1

# nginx config.
COPY .docker/images/nginx/helpers/ /etc/nginx/helpers/
COPY .docker/images/nginx/x_frame_options.conf /etc/nginx/conf.d/drupal/location_drupal_append_x_frame_options.conf
COPY .docker/images/nginx/no-robots.sh /lagoon/entrypoints/20-no-robots.sh
RUN fix-permissions /etc/nginx

COPY --from=cli /app /app
COPY .docker/sanitize.sh /app/sanitize.sh

RUN /app/sanitize.sh \
  && rm -rf /app/sanitize.sh
