#!/usr/bin/env bash
##
# GovCMS 8 Drupal deployment script.
#

# Ensure placeholders are replaced in Drush9 alias file.
sed -i "s/%%PROJECT_NAME%%/$LAGOON_PROJECT/g" /app/drush/sites/govcms.site.yml

# Ensure tmp folder always exists.
mkdir -p /app/web/sites/default/files/private/tmp/

# Check for presence of config files.
config_count=`ls -1 /app/config/default/* 2>/dev/null | wc -l`

# All valid environments.
if drush status --fields=bootstrap | grep -q "Successful"; then
  drush updb -y
  drush cr
fi

# Non production environments.
if [[ "$LAGOON_ENVIRONMENT_TYPE" != "production" ]]; then
    # Import production database on inital deployment.
    if ! drush status --fields=bootstrap | grep -q "Successful"; then

        # SQL sync only in Lagoon development environments.
        if [[ ! -z "$LAGOON_ENVIRONMENT_TYPE" && "$LAGOON_ENVIRONMENT_TYPE" != "local" ]]; then
          drush sql-sync @govcms.prod @self -y

          # Base configuration import with development environment overrides.
          if [ "$config_count" -gt 1 ]; then
            drush cim -y sync
            drush cim -y dev --partial
          fi

          # Enable stage file proxy post db-import.
          drush en stage_file_proxy -y
        fi

    else
      # Base configuration import with development environment overrides.
      if [ "$config_count" -gt 1 ]; then
        drush cim -y sync
        drush cim -y dev --partial
      fi

      # Enable stage file proxy.
      drush en stage_file_proxy -y
    fi

# Production environments.
else

  if drush status --fields=bootstrap | grep -q "Successful"; then
    mkdir -p /app/web/sites/default/files/private/backups/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/backups/pre-deploy-dump.sql
    # Configuration import.
    if [ "$config_count" -gt 1 ]; then
      drush cim -y sync
    fi

    drush en -y govcms_lagoon && drush pmu -y govcms_lagoon;

  else
    echo "Drupal not installed."
  fi

fi
